apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hz52ffj5z-go 
  janus-idp.io/tekton: hz52ffj5z-go
  backstage.io/kubernetes-id: hz52ffj5z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hz52ffj5z-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml